// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/8c9d2af6b3aa98491ac8996a299bf4715715fd73/jsx-chai/jsx-chai.d.ts
declare module 'jsx-chai' {
    interface JsxChaiStatic {
        jsxChai: jsxChaiFunction;
    }

    interface jsxChaiFunction {
        (chai: any, utils: any): void;
    }

    var jsxChai: JsxChaiStatic;

    export = jsxChai;
}
