// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/d417f687ab0c81ed72bffbc5dace5f643369bb70/redux-devtools/redux-devtools.d.ts
declare module "redux-devtools" {
  import * as React from 'react'

  interface IDevTools {
    new (): JSX.ElementClass
    instrument(): (opts: any) => any;
  }

  export function createDevTools(el: React.ReactElement<any>): IDevTools
  export function persistState(debugSessionKey: string): Function

  var factory: { instrument(): (opts: any) => any }

  export default factory;
}
