// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/expect/expect.d.ts
declare module "expect" {

  type IExpectFactory = (actual:any) => Expect.Expectation;
  const expect: IExpect & IExpectFactory;

  interface IExpect {
    createSpy(fn?: Function, restore?: Function): Spy;
    spyOn(object: Object, methodName: string): Spy;
    isSpy(object: any): Boolean;
    restoreSpies(): void;
    assert(condition: any, messageFormat: string, ...extraArgs: Array<any>): void;
    extend(extension: Expect.Extension): void;
  }

  export = expect;
}
